### ISSUE TITLE
Info logger in Boto3Strategy

### ISSUE THREAD

**Issue by schabowsky** [antonagestam/collectfast#214] opened 2021-12-03 08:54 UTC
Using `colllectstatic` command with `collectfast.strategies.boto3.Boto3Strategy` and `COLLECTFAST_THREADS` > 1 prints a lot of messages in console. 

https://github.com/antonagestam/collectfast/blob/5df47b94821517cfbb0e7b9fe09198a4d4a4db92/collectfast/strategies/boto3.py#L45

Could you remove it? Or at least change log level to DEBUG? It's a bit annoying when you upload many files.

**Comment by antonagestam** [comment] 2021-12-03 09:00
I consider this a duplicate of https://github.com/antonagestam/collectfast/issues/138, feel free to comment there.

> Could you remove it? 

No, but I can review and merge well-shaped PRs.

**Closed as completed by antonagestam** 2021-12-03 09:00 UTC

**Comment by schabowsky** [comment] 2021-12-03 14:57
@antonagestam PR already created https://github.com/antonagestam/collectfast/pull/215
